
name: Publish IceCream Functions

on:
  # Only run manually
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'api3-icecream-faapi' # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'           # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.8'                         # set this to the python version to use (supports 3.6, 3.7, 3.8)
  AZURE_RESOURCE_GROUP: 'api3-iceCream-api'     # Resource Group name

jobs:
  deploy_function:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Azure CLI Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZSPRATINGSAPI}}
        enable-AzPSSession: false

    - name: Update Function App settings
      run: |
        az functionapp config appsettings set --name ${{env.AZURE_FUNCTIONAPP_NAME}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --settings cosmosendpoint=
        az functionapp config appsettings set --name ${{env.AZURE_FUNCTIONAPP_NAME}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --settings cosmoskey=

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    
